// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import BookController from "./book_controller"
application.register("book", BookController)

import FlashController from "./flash_controller"
application.register("flash_message", FlashController)

import ToogleController from "./toogle_controller"
application.register("toogle", ToogleController)
